CREATE TABLE IF NOT EXISTS rascunhos_itens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    patrimonio_novo VARCHAR(100) NULL,
    local_id INT NULL,
    responsavel_id INT NULL,
    estado ENUM('Em uso', 'Ocioso', 'Recuperável', 'Inservível') DEFAULT 'Em uso',
    observacao TEXT,
    descricao_detalhada TEXT,
    numero_serie VARCHAR(100),
    quantidade INT DEFAULT 1,
    valor DECIMAL(10, 2),
    nota_fiscal_documento VARCHAR(100),
    data_entrada_aceitacao DATE,
    empenho_id INT NULL,
    empenho VARCHAR(100),
    data_emissao_empenho DATE,
    fornecedor VARCHAR(255),
    cnpj_fornecedor VARCHAR(18),
    categoria VARCHAR(255),
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (local_id) REFERENCES locais(id) ON DELETE SET NULL,
    FOREIGN KEY (responsavel_id) REFERENCES usuarios(id) ON DELETE SET NULL,
    FOREIGN KEY (empenho_id) REFERENCES empenhos(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;